"""Contract test: live OpenAPI spec must not introduce breaking changes vs committed snapshot.

Uses oasdiff to detect breaking changes between openapi.json (committed snapshot) and
the spec generated by the running app (via TestClient).
"""
import json
import subprocess
import tempfile
from pathlib import Path

import pytest
from fastapi.testclient import TestClient

from fraudstream.serving.app import create_app
from fraudstream.serving.model_loader import ModelLoader
from fraudstream.serving.prediction_logger import PredictionLogger

SNAPSHOT_PATH = Path(__file__).parent.parent.parent / "openapi.json"


@pytest.fixture(scope="module")
def client() -> TestClient:
    app = create_app(loader=ModelLoader(), prediction_logger=PredictionLogger())
    return TestClient(app, raise_server_exceptions=False)


def test_openapi_snapshot_exists() -> None:
    assert SNAPSHOT_PATH.exists(), (
        f"openapi.json snapshot not found at {SNAPSHOT_PATH}. "
        "Run: python -c \"from fraudstream.serving.app import create_app; "
        "import json; print(json.dumps(create_app().openapi()))\" > openapi.json"
    )


def test_no_breaking_changes(client: TestClient) -> None:
    try:
        result = subprocess.run(["oasdiff", "--version"], capture_output=True)
        if result.returncode != 0:
            pytest.skip("oasdiff not installed")
    except FileNotFoundError:
        pytest.skip("oasdiff not installed")

    resp = client.get("/openapi.json")
    assert resp.status_code == 200

    live_spec = resp.json()
    with tempfile.NamedTemporaryFile(suffix=".json", mode="w", delete=False) as f:
        json.dump(live_spec, f)
        live_path = f.name

    result = subprocess.run(
        ["oasdiff", "breaking", str(SNAPSHOT_PATH), live_path],
        capture_output=True,
        text=True,
    )
    assert result.returncode == 0, (
        f"Breaking API changes detected:\n{result.stdout}\n{result.stderr}"
    )
